<?php
$sectionLoadConfig = $block->getJsonEncodedWidgetConfig();
$isLoggedIn = $block->isLoggedIn();
$ajaxcianSelectors = [
    '.action.tocart',
    '.ajaxpro-modal-dialog #shopping-cart-table .action-delete',
    // '.ajaxpro-modal-dialog #shopping-cart-table .cart.actions .update',
    '.action.tocompare',
    '.block-compare .action.delete',
    // '.table-comparison .action.delete',
];
if ($isLoggedIn) {
    $ajaxcianSelectors[] = '.action.towishlist';
    $ajaxcianSelectors[] = '.ajaxpro-modal-dialog #shopping-cart-table .action.action-towishlist';
    // $ajaxcianSelectors[] = '.products-grid.wishlist .action.tocart';
    $ajaxcianSelectors[] = '.block-wishlist .action.delete';
    $ajaxcianSelectors[] = '.block-wishlist .action.tocart';
}
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout();?>,
        <?php if ($block->isQuickViewEnabled()) :
            ?>"Swissup_Ajaxpro/js/quick-view": <?= /* @noEscape */ $sectionLoadConfig ?>,
        <?php endif;
        if ($block->isAnimationEnabled()) :
            ?>"Swissup_Ajaxpro/js/view/animation": [],
        <?php endif;
        ?>"Swissup_Ajaxpro/js/catalog-product-view": <?= /* @noEscape */ $sectionLoadConfig ?>
    },
    "<?= /* @noEscape */ implode(', ', $ajaxcianSelectors) ?>": {
        "Swissup_Ajaxpro/js/ajaxcian-data-post": {
            "loaderImage": "<?= /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif'); ?>",
            "loaderImageMaxWidth": "20px"
        }
    }
}
</script>
